// source: client.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.PongBackend.v1.client.ClientResponse', null, global);
goog.exportSymbol('proto.PongBackend.v1.client.ClientResponse.ResponseCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.PongBackend.v1.client.ClientResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.PongBackend.v1.client.ClientResponse.oneofGroups_);
};
goog.inherits(proto.PongBackend.v1.client.ClientResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.PongBackend.v1.client.ClientResponse.displayName = 'proto.PongBackend.v1.client.ClientResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.PongBackend.v1.client.ClientResponse.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.PongBackend.v1.client.ClientResponse.ResponseCase = {
  RESPONSE_NOT_SET: 0,
  PING: 1,
  CONNECTED: 2,
  POSITION: 3
};

/**
 * @return {proto.PongBackend.v1.client.ClientResponse.ResponseCase}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.getResponseCase = function() {
  return /** @type {proto.PongBackend.v1.client.ClientResponse.ResponseCase} */(jspb.Message.computeOneofCase(this, proto.PongBackend.v1.client.ClientResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.PongBackend.v1.client.ClientResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.PongBackend.v1.client.ClientResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PongBackend.v1.client.ClientResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    ping: (f = msg.getPing()) && common_pb.Ping.toObject(includeInstance, f),
    connected: (f = msg.getConnected()) && common_pb.Connected.toObject(includeInstance, f),
    position: (f = msg.getPosition()) && common_pb.Position.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.PongBackend.v1.client.ClientResponse}
 */
proto.PongBackend.v1.client.ClientResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.PongBackend.v1.client.ClientResponse;
  return proto.PongBackend.v1.client.ClientResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.PongBackend.v1.client.ClientResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.PongBackend.v1.client.ClientResponse}
 */
proto.PongBackend.v1.client.ClientResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.Ping;
      reader.readMessage(value,common_pb.Ping.deserializeBinaryFromReader);
      msg.setPing(value);
      break;
    case 2:
      var value = new common_pb.Connected;
      reader.readMessage(value,common_pb.Connected.deserializeBinaryFromReader);
      msg.setConnected(value);
      break;
    case 3:
      var value = new common_pb.Position;
      reader.readMessage(value,common_pb.Position.deserializeBinaryFromReader);
      msg.setPosition(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.PongBackend.v1.client.ClientResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.PongBackend.v1.client.ClientResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.PongBackend.v1.client.ClientResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPing();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.Ping.serializeBinaryToWriter
    );
  }
  f = message.getConnected();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_pb.Connected.serializeBinaryToWriter
    );
  }
  f = message.getPosition();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_pb.Position.serializeBinaryToWriter
    );
  }
};


/**
 * optional PongBackend.v1.common.Ping ping = 1;
 * @return {?proto.PongBackend.v1.common.Ping}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.getPing = function() {
  return /** @type{?proto.PongBackend.v1.common.Ping} */ (
    jspb.Message.getWrapperField(this, common_pb.Ping, 1));
};


/**
 * @param {?proto.PongBackend.v1.common.Ping|undefined} value
 * @return {!proto.PongBackend.v1.client.ClientResponse} returns this
*/
proto.PongBackend.v1.client.ClientResponse.prototype.setPing = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.PongBackend.v1.client.ClientResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PongBackend.v1.client.ClientResponse} returns this
 */
proto.PongBackend.v1.client.ClientResponse.prototype.clearPing = function() {
  return this.setPing(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.hasPing = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional PongBackend.v1.common.Connected connected = 2;
 * @return {?proto.PongBackend.v1.common.Connected}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.getConnected = function() {
  return /** @type{?proto.PongBackend.v1.common.Connected} */ (
    jspb.Message.getWrapperField(this, common_pb.Connected, 2));
};


/**
 * @param {?proto.PongBackend.v1.common.Connected|undefined} value
 * @return {!proto.PongBackend.v1.client.ClientResponse} returns this
*/
proto.PongBackend.v1.client.ClientResponse.prototype.setConnected = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.PongBackend.v1.client.ClientResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PongBackend.v1.client.ClientResponse} returns this
 */
proto.PongBackend.v1.client.ClientResponse.prototype.clearConnected = function() {
  return this.setConnected(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.hasConnected = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PongBackend.v1.common.Position position = 3;
 * @return {?proto.PongBackend.v1.common.Position}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.getPosition = function() {
  return /** @type{?proto.PongBackend.v1.common.Position} */ (
    jspb.Message.getWrapperField(this, common_pb.Position, 3));
};


/**
 * @param {?proto.PongBackend.v1.common.Position|undefined} value
 * @return {!proto.PongBackend.v1.client.ClientResponse} returns this
*/
proto.PongBackend.v1.client.ClientResponse.prototype.setPosition = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.PongBackend.v1.client.ClientResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.PongBackend.v1.client.ClientResponse} returns this
 */
proto.PongBackend.v1.client.ClientResponse.prototype.clearPosition = function() {
  return this.setPosition(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.PongBackend.v1.client.ClientResponse.prototype.hasPosition = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.PongBackend.v1.client);
