// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: embeded.proto

package protoEmbeded

import (
	common "github.com/polis-interactive/Pong/pong-backend/api/v1/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbededRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*EmbededRequest_Pong
	//	*EmbededRequest_Position
	Request isEmbededRequest_Request `protobuf_oneof:"request"`
}

func (x *EmbededRequest) Reset() {
	*x = EmbededRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embeded_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbededRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbededRequest) ProtoMessage() {}

func (x *EmbededRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embeded_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbededRequest.ProtoReflect.Descriptor instead.
func (*EmbededRequest) Descriptor() ([]byte, []int) {
	return file_embeded_proto_rawDescGZIP(), []int{0}
}

func (m *EmbededRequest) GetRequest() isEmbededRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *EmbededRequest) GetPong() *common.Pong {
	if x, ok := x.GetRequest().(*EmbededRequest_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *EmbededRequest) GetPosition() *common.Position {
	if x, ok := x.GetRequest().(*EmbededRequest_Position); ok {
		return x.Position
	}
	return nil
}

type isEmbededRequest_Request interface {
	isEmbededRequest_Request()
}

type EmbededRequest_Pong struct {
	Pong *common.Pong `protobuf:"bytes,1,opt,name=pong,proto3,oneof"`
}

type EmbededRequest_Position struct {
	Position *common.Position `protobuf:"bytes,2,opt,name=position,proto3,oneof"`
}

func (*EmbededRequest_Pong) isEmbededRequest_Request() {}

func (*EmbededRequest_Position) isEmbededRequest_Request() {}

type EmbededResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*EmbededResponse_Ping
	//	*EmbededResponse_Connected
	Response isEmbededResponse_Response `protobuf_oneof:"response"`
}

func (x *EmbededResponse) Reset() {
	*x = EmbededResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embeded_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbededResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbededResponse) ProtoMessage() {}

func (x *EmbededResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embeded_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbededResponse.ProtoReflect.Descriptor instead.
func (*EmbededResponse) Descriptor() ([]byte, []int) {
	return file_embeded_proto_rawDescGZIP(), []int{1}
}

func (m *EmbededResponse) GetResponse() isEmbededResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *EmbededResponse) GetPing() *common.Ping {
	if x, ok := x.GetResponse().(*EmbededResponse_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *EmbededResponse) GetConnected() *common.Connected {
	if x, ok := x.GetResponse().(*EmbededResponse_Connected); ok {
		return x.Connected
	}
	return nil
}

type isEmbededResponse_Response interface {
	isEmbededResponse_Response()
}

type EmbededResponse_Ping struct {
	Ping *common.Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type EmbededResponse_Connected struct {
	Connected *common.Connected `protobuf:"bytes,2,opt,name=connected,proto3,oneof"`
}

func (*EmbededResponse_Ping) isEmbededResponse_Response() {}

func (*EmbededResponse_Connected) isEmbededResponse_Response() {}

var File_embeded_proto protoreflect.FileDescriptor

var file_embeded_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x16, 0x50, 0x6f, 0x6e, 0x67, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x65, 0x6d, 0x62, 0x65, 0x64, 0x65, 0x64, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x0e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x42, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50,
	0x6f, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x3d, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e,
	0x50, 0x6f, 0x6e, 0x67, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x0f, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x70, 0x69, 0x6e,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a, 0x09,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6c, 0x69, 0x73, 0x2d, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x2f, 0x50, 0x6f, 0x6e, 0x67, 0x2f,
	0x70, 0x6f, 0x6e, 0x67, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x67, 0x6f, 0x2f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x65, 0x64, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_embeded_proto_rawDescOnce sync.Once
	file_embeded_proto_rawDescData = file_embeded_proto_rawDesc
)

func file_embeded_proto_rawDescGZIP() []byte {
	file_embeded_proto_rawDescOnce.Do(func() {
		file_embeded_proto_rawDescData = protoimpl.X.CompressGZIP(file_embeded_proto_rawDescData)
	})
	return file_embeded_proto_rawDescData
}

var file_embeded_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_embeded_proto_goTypes = []interface{}{
	(*EmbededRequest)(nil),   // 0: PongBackend.v1.embeded.EmbededRequest
	(*EmbededResponse)(nil),  // 1: PongBackend.v1.embeded.EmbededResponse
	(*common.Pong)(nil),      // 2: PongBackend.v1.common.Pong
	(*common.Position)(nil),  // 3: PongBackend.v1.common.Position
	(*common.Ping)(nil),      // 4: PongBackend.v1.common.Ping
	(*common.Connected)(nil), // 5: PongBackend.v1.common.Connected
}
var file_embeded_proto_depIdxs = []int32{
	2, // 0: PongBackend.v1.embeded.EmbededRequest.pong:type_name -> PongBackend.v1.common.Pong
	3, // 1: PongBackend.v1.embeded.EmbededRequest.position:type_name -> PongBackend.v1.common.Position
	4, // 2: PongBackend.v1.embeded.EmbededResponse.ping:type_name -> PongBackend.v1.common.Ping
	5, // 3: PongBackend.v1.embeded.EmbededResponse.connected:type_name -> PongBackend.v1.common.Connected
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_embeded_proto_init() }
func file_embeded_proto_init() {
	if File_embeded_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_embeded_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbededRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_embeded_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbededResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_embeded_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*EmbededRequest_Pong)(nil),
		(*EmbededRequest_Position)(nil),
	}
	file_embeded_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*EmbededResponse_Ping)(nil),
		(*EmbededResponse_Connected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_embeded_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_embeded_proto_goTypes,
		DependencyIndexes: file_embeded_proto_depIdxs,
		MessageInfos:      file_embeded_proto_msgTypes,
	}.Build()
	File_embeded_proto = out.File
	file_embeded_proto_rawDesc = nil
	file_embeded_proto_goTypes = nil
	file_embeded_proto_depIdxs = nil
}
