/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "api/common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PongBackend_v1_common_EmptyRequest, PongBackend_v1_common_EmptyRequest, AUTO)


PB_BIND(PongBackend_v1_common_EmptyResponse, PongBackend_v1_common_EmptyResponse, AUTO)


PB_BIND(PongBackend_v1_common_Ping, PongBackend_v1_common_Ping, AUTO)


PB_BIND(PongBackend_v1_common_Pong, PongBackend_v1_common_Pong, AUTO)


PB_BIND(PongBackend_v1_common_Connected, PongBackend_v1_common_Connected, AUTO)


PB_BIND(PongBackend_v1_common_Position, PongBackend_v1_common_Position, AUTO)



