/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "api/embeded.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PongBackend_v1_embeded_EmbededRequest, PongBackend_v1_embeded_EmbededRequest, AUTO)


PB_BIND(PongBackend_v1_embeded_EmbededResponse, PongBackend_v1_embeded_EmbededResponse, AUTO)



