/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "embedded.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PongBackend_v1_embedded_EmbeddedRequest, PongBackend_v1_embedded_EmbeddedRequest, AUTO)


PB_BIND(PongBackend_v1_embedded_EmbeddedResponse, PongBackend_v1_embedded_EmbeddedResponse, AUTO)



