/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_PONGBACKEND_V1_COMMON_COMMON_PB_H_INCLUDED
#define PB_PONGBACKEND_V1_COMMON_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PongBackend_v1_common_EmptyRequest { 
    char dummy_field;
} PongBackend_v1_common_EmptyRequest;

typedef struct _PongBackend_v1_common_EmptyResponse { 
    char dummy_field;
} PongBackend_v1_common_EmptyResponse;

typedef struct _PongBackend_v1_common_Ping { 
    char dummy_field;
} PongBackend_v1_common_Ping;

typedef struct _PongBackend_v1_common_Pong { 
    char dummy_field;
} PongBackend_v1_common_Pong;

typedef struct _PongBackend_v1_common_Connected { 
    bool connected; 
} PongBackend_v1_common_Connected;

typedef struct _PongBackend_v1_common_Position { 
    uint32_t position; 
} PongBackend_v1_common_Position;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PongBackend_v1_common_EmptyRequest_init_default {0}
#define PongBackend_v1_common_EmptyResponse_init_default {0}
#define PongBackend_v1_common_Ping_init_default  {0}
#define PongBackend_v1_common_Pong_init_default  {0}
#define PongBackend_v1_common_Connected_init_default {0}
#define PongBackend_v1_common_Position_init_default {0}
#define PongBackend_v1_common_EmptyRequest_init_zero {0}
#define PongBackend_v1_common_EmptyResponse_init_zero {0}
#define PongBackend_v1_common_Ping_init_zero     {0}
#define PongBackend_v1_common_Pong_init_zero     {0}
#define PongBackend_v1_common_Connected_init_zero {0}
#define PongBackend_v1_common_Position_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define PongBackend_v1_common_Connected_connected_tag 1
#define PongBackend_v1_common_Position_position_tag 1

/* Struct field encoding specification for nanopb */
#define PongBackend_v1_common_EmptyRequest_FIELDLIST(X, a) \

#define PongBackend_v1_common_EmptyRequest_CALLBACK NULL
#define PongBackend_v1_common_EmptyRequest_DEFAULT NULL

#define PongBackend_v1_common_EmptyResponse_FIELDLIST(X, a) \

#define PongBackend_v1_common_EmptyResponse_CALLBACK NULL
#define PongBackend_v1_common_EmptyResponse_DEFAULT NULL

#define PongBackend_v1_common_Ping_FIELDLIST(X, a) \

#define PongBackend_v1_common_Ping_CALLBACK NULL
#define PongBackend_v1_common_Ping_DEFAULT NULL

#define PongBackend_v1_common_Pong_FIELDLIST(X, a) \

#define PongBackend_v1_common_Pong_CALLBACK NULL
#define PongBackend_v1_common_Pong_DEFAULT NULL

#define PongBackend_v1_common_Connected_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     connected,         1)
#define PongBackend_v1_common_Connected_CALLBACK NULL
#define PongBackend_v1_common_Connected_DEFAULT NULL

#define PongBackend_v1_common_Position_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   position,          1)
#define PongBackend_v1_common_Position_CALLBACK NULL
#define PongBackend_v1_common_Position_DEFAULT NULL

extern const pb_msgdesc_t PongBackend_v1_common_EmptyRequest_msg;
extern const pb_msgdesc_t PongBackend_v1_common_EmptyResponse_msg;
extern const pb_msgdesc_t PongBackend_v1_common_Ping_msg;
extern const pb_msgdesc_t PongBackend_v1_common_Pong_msg;
extern const pb_msgdesc_t PongBackend_v1_common_Connected_msg;
extern const pb_msgdesc_t PongBackend_v1_common_Position_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PongBackend_v1_common_EmptyRequest_fields &PongBackend_v1_common_EmptyRequest_msg
#define PongBackend_v1_common_EmptyResponse_fields &PongBackend_v1_common_EmptyResponse_msg
#define PongBackend_v1_common_Ping_fields &PongBackend_v1_common_Ping_msg
#define PongBackend_v1_common_Pong_fields &PongBackend_v1_common_Pong_msg
#define PongBackend_v1_common_Connected_fields &PongBackend_v1_common_Connected_msg
#define PongBackend_v1_common_Position_fields &PongBackend_v1_common_Position_msg

/* Maximum encoded size of messages (where known) */
#define PongBackend_v1_common_Connected_size     2
#define PongBackend_v1_common_EmptyRequest_size  0
#define PongBackend_v1_common_EmptyResponse_size 0
#define PongBackend_v1_common_Ping_size          0
#define PongBackend_v1_common_Pong_size          0
#define PongBackend_v1_common_Position_size      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
